apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notes-staging
resources:
- ../../base
  # Phase 9 加了 api 之後這裡會變成兩筆
images:
- name: ghcr.io/liaooliver/notes
  newName: ghcr.io/liaooliver/notes
  newTag: sha-082ff2eb59bc6ba97bcb01ec7236867ed4e9a075
- name: ghcr.io/liaooliver/notes-api
  newName: ghcr.io/liaooliver/notes-api
  newTag: sha-082ff2eb59bc6ba97bcb01ec7236867ed4e9a075
patches:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: notes-staging.local
  target:
    kind: Ingress
    name: notes
