apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notes-production
resources:
- ../../base
images:
- name: ghcr.io/liaooliver/notes
  newName: ghcr.io/liaooliver/notes
  newTag: sha-91b7f1149b02d469b145af0245da53311d7d8ae5
- name: ghcr.io/liaooliver/notes-api
  newName: ghcr.io/liaooliver/notes-api
  newTag: sha-91b7f1149b02d469b145af0245da53311d7d8ae5
patches:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: notes.local
  target:
    kind: Ingress
    name: notes
